#!/bin/bash
wget http://www.airspayce.com/mikem/bcm2835/bcm2835-1.70.tar.gz
tar zxvf bcm2835-1.70.tar.gz 
cd bcm2835-1.70/
sudo ./configure
sudo make && sudo make check && sudo make install
cd ../
sudo rm -r bcm2835-1.70
sudo rm -r bcm2835-1.70.tar.gz
